# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod vendor
    - go generate ./...
builds:
  - goos:
      - linux
      - darwin
      - openbsd
      - freebsd
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    env:
      - CGO_ENABLED=0
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ .Tag }}-next'
