language: go

sudo: required

go:
  - master

before_install:
  - wget -O /tmp/gommit https://github.com/antham/gommit/releases/download/v2.0.0/gommit_linux_386 && chmod 777 /tmp/gommit
  - export PATH=$PATH:/tmp/
  - go get github.com/Masterminds/glide
  - go get -u github.com/golang/dep/cmd/dep
  - go get github.com/alecthomas/gometalinter
  - gometalinter --install --update
  - gommit

install: dep ensure -v

script: make test-all && perl test-branch-commit-messages-in-travis.pl

after_success:
  - bash <(curl -s https://codecov.io/bash)
