version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/antham/gommit
    environment:
      BASH_ENV: /home/circleci/.bashrc
    steps:
      - checkout
      - run:
          name: Get gommit binary
          command: |
            sudo curl -L -o /usr/local/bin/gommit https://github.com/antham/gommit/releases/download/v2.1.1/gommit_linux_386
            sudo chmod 777 /usr/local/bin/gommit
            curl -sL https://github.com/goreleaser/goreleaser/releases/download/v0.123.3/goreleaser_Linux_x86_64.tar.gz|sudo tar -C /usr/local/bin/ -xzv goreleaser
      - run:
          name: Install vendors
          command: |
            export GO111MODULE=on
            go mod download
      - run:
          name: Check go mod tidy doesn't produce diff
          command: |
            test $(go mod tidy -v 2>&1|wc -l) -eq 0 || exit 1
      - run:
          name: Compile
          command: |
            goreleaser release --skip-publish --rm-dist --snapshot
      - run:
          name: Run tests
          command: |
            make test-all
      - run:
          name: Run gommit
          command: |
            if [ $CIRCLE_BRANCH != 'master' ]; then gommit check range $(git rev-parse origin/master) $CIRCLE_BRANCH ; fi
      - run:
          name: Push on codecov result
          command: |
            bash <(curl -s https://codecov.io/bash)

  publish:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/antham/gommit
    steps:
      - checkout
      - run:
          name: Fetch tags
          command: |
            git fetch --tags
      - run:
          name: Install dependencies
          command: |
            mkdir /home/circleci/bin
            wget -O ~/bin/chyle https://github.com/antham/chyle/releases/download/v1.2.0/chyle_linux_amd64
            chmod 777 ~/bin/chyle
            curl -sL https://github.com/goreleaser/goreleaser/releases/download/v0.123.3/goreleaser_Linux_x86_64.tar.gz|sudo tar -C /usr/local/bin/  -xzv goreleaser
      - run:
          name: Install vendors
          command: |
            export GO111MODULE=on
      - run:
          name: Compile
          command: |
            goreleaser release
      - run:
          name: Run chyle
          command: |
            FROM_TAG=$(git tag -l --sort=-v:refname|head -n 2|tail -n 1)
            TO_TAG=$(git tag -l --sort=-v:refname|head -n 1)
            export CHYLE_GIT_REPOSITORY_PATH="."
            export CHYLE_GIT_REFERENCE_FROM="$(git rev-parse $FROM_TAG)"
            export CHYLE_GIT_REFERENCE_TO="$(git rev-parse $TO_TAG)"
            export CHYLE_MATCHERS_TYPE="merge"
            export CHYLE_EXTRACTORS_GITHUBISSUEID_ORIGKEY="message"
            export CHYLE_EXTRACTORS_GITHUBISSUEID_DESTKEY="githubIssueId"
            export CHYLE_EXTRACTORS_GITHUBISSUEID_REG="#(\\d+)"
            export CHYLE_DECORATORS_GITHUBISSUE_CREDENTIALS_OWNER="antham"
            export CHYLE_DECORATORS_GITHUBISSUE_CREDENTIALS_OAUTHTOKEN="$GITHUB_TOKEN"
            export CHYLE_DECORATORS_GITHUBISSUE_KEYS_TITLE_DESTKEY="issueTitle"
            export CHYLE_DECORATORS_GITHUBISSUE_KEYS_TITLE_FIELD="title"
            export CHYLE_DECORATORS_GITHUBISSUE_REPOSITORY_NAME="$CIRCLE_PROJECT_REPONAME"

            export CHYLE_SENDERS_GITHUBRELEASE_CREDENTIALS_OAUTHTOKEN="$GITHUB_TOKEN"
            export CHYLE_SENDERS_GITHUBRELEASE_CREDENTIALS_OWNER="antham"
            export CHYLE_SENDERS_GITHUBRELEASE_RELEASE_TAGNAME="$TO_TAG"
            export CHYLE_SENDERS_GITHUBRELEASE_RELEASE_UPDATE="true"
            export CHYLE_SENDERS_GITHUBRELEASE_REPOSITORY_NAME="$CIRCLE_PROJECT_REPONAME"
            export CHYLE_SENDERS_GITHUBRELEASE_RELEASE_TEMPLATE='### Changes
            {{ range $key, $value := .Datas }}
            => {{ $value.issueTitle }} (#{{ $value.githubIssueId }}) {{ end }}'

            ~/bin/chyle create

workflows:
  version: 2
  build:
    jobs:
      - build
  publish:
    jobs:
      - publish:
          context: org-global
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
