version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/antham/gommit
    environment:
       BASH_ENV: /home/circleci/.bashrc
    steps:
      - checkout
      - run:
          name: Get gommit binary
          command: |
            mkdir /home/circleci/bin
            wget -O ~/bin/gommit https://github.com/antham/gommit/releases/download/v2.1.3/gommit_linux_386 && chmod 777 ~/bin/gommit
      - run:
          name: Install gometalinter
          command: |
            go get github.com/alecthomas/gometalinter
            gometalinter --install --update
      - run:
          name: Install vendors
          command: |
            export GO111MODULE=on
            go mod vendor
      - run:
          name: Run tests
          command: |
            make test-all
      - run:
          name: Run gommit
          command: |
            if [ $CIRCLE_BRANCH != 'master' ]; then ~/bin/gommit check range $(git rev-parse origin/master) $CIRCLE_BRANCH ; fi
      - run:
          name: Push on codecov result
          command: |
            bash <(curl -s https://codecov.io/bash)
